name: new_env
channels:
  - bioconda
  - milaboratories
  - schrodinger
  - defaults
  - conda-forge
  - omnia
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - nodefaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.13=hb9d3cd8_0
  - apbs=1.5=hd8ae8d1_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - attr=2.5.1=h166bdaf_1
  - bfee2=3.0.0=pyhd8ed1ab_1
  - biopython=1.84=py310hc51659f_0
  - blosc=1.21.6=he440d0b_1
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py310hf71b8c6_2
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.0=h3faef2a_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=1.17.1=py310h8deb56e_0
  - cftime=1.6.4=py310hf462985_1
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - collada2gltf=2.1.4=h6bb024c_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.1=py310h3788b33_0
  - cudatoolkit=11.8.0=h4ba93d1_13
  - curl=8.11.1=h332b0f4_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dbus=1.13.6=h5008d03_3
  - double-conversion=3.3.1=h5888daf_0
  - expat=2.6.4=h5888daf_0
  - fasteners=0.19=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.55.3=py310h89163eb_1
  - freetype=2.12.1=h267a509_2
  - gettext=0.23.1=h5888daf_0
  - gettext-tools=0.23.1=h5888daf_0
  - giflib=5.2.2=hd590300_0
  - glew=2.1.0=h9c3ff4c_2
  - glib=2.78.1=hfc55251_0
  - glib-tools=2.78.1=hfc55251_0
  - graphite2=1.3.13=h59595ed_1003
  - griddataformats=1.0.2=pyhd8ed1ab_1
  - gsd=3.4.2=py310ha75aee5_0
  - gst-plugins-base=1.22.7=h8e1006c_0
  - gstreamer=1.22.7=h98fc4e7_0
  - h2=4.2.0=pyhd8ed1ab_0
  - h5py=3.13.0=nompi_py310h60e0fe6_100
  - harfbuzz=8.3.0=h3d44ed6_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.3=nompi_h2d575fe_109
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.10=pyhd8ed1ab_1
  - joblib=1.4.2=pyhd8ed1ab_1
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h27087fc_0
  - matplotlib-base=3.10.0=py310h68603db_0
  - mda-xdrlib=0.2.0=pyhd8ed1ab_1
  - mdahole2-base=0.5.0=pyhd8ed1ab_1
  - mdanalysis=2.8.0=py310h5eaa309_0
  - mengine=1=h14c3975_1
  - mesa-libgl-cos7-x86_64=18.3.4=ha675448_1106
  - mesa-libglapi-cos7-x86_64=18.3.4=ha675448_1106
  - mixcr=4.7.0=0
  - mmcif_pdbx=2.0.1=pyhd8ed1ab_1
  - mmtf-python=1.1.3=pyhd8ed1ab_0
  - mpeg_encode=1=h14c3975_1
  - mpg123=1.32.9=hc50e24c_0
  - mrcfile=1.5.3=pyhd8ed1ab_1
  - msgpack-python=1.1.0=py310h3788b33_0
  - mtz2ccp4_px=1.1=h3218e01_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.33=hf1915f5_6
  - mysql-libs=8.0.33=hca2cd23_6
  - ncbi-vdb=3.2.1=h9948957_0
  - ncurses=6.5=he02047a_1
  - netcdf4=1.7.2=nompi_py310h9f0ad05_101
  - networkx=3.4.2=pyh267e887_2
  - nlohmann_json=3.11.3=he02047a_1
  - nspr=4.36=h5888daf_0
  - nss=3.107=hdf54f9c_0
  - numpy=2.2.6=py310hefbff90_0
  - ocl-icd=2.3.2=hb9d3cd8_2
  - ocl-icd-system=1.0.0=1
  - openbabel=3.1.1=py310h956b46e_8
  - opencl-headers=2024.10.24=h5888daf_0
  - openjdk=21.0.2=haa376d0_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openmm=8.2.0=py310h30bdd6a_2
  - openssl=3.5.4=h26f9b46_0
  - ossuuid=1.6.2=h5888daf_1001
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py310h5eaa309_1
  - parmed=4.3.0=py310h78e4988_2
  - pathsimanalysis=1.2.0=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.40=hc3806b6_0
  - pdb2pqr=3.6.1=pyhd8ed1ab_1
  - pdbfixer=1.11=pyhd8ed1ab_0
  - perl=5.22.2.1=0
  - perl-threaded=5.32.1=hdfd78af_1
  - perl-uri=1.71=0
  - perl-xml-libxml=2.0124=0
  - perl-xml-namespacesupport=1.11=0
  - perl-xml-sax=0.99=0
  - perl-xml-sax-base=1.08=0
  - pip=24.2=py310h06a4308_0
  - pixman=0.44.2=h29eaf8c_0
  - ply=3.11=pyhd8ed1ab_3
  - pmw=2.0.1=py310hff52083_1008
  - propka=3.5.1=pyhecae5ae_2
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pulseaudio-client=16.1=hb77b528_5
  - pycollada=0.9=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pyedr=0.8.0=pyhd8ed1ab_1
  - pykerberos=1.2.4=py310h695cd88_6
  - pyparsing=3.2.1=pyhd8ed1ab_0
  - pyqt=5.15.9=py310h04931ad_5
  - pyqt5-sip=12.12.2=py310hc6cd4ac_5
  - pyside6=6.6.1=py310h1570d6a_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.16=he725a3c_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2024.2=pyhd8ed1ab_1
  - python_abi=3.10=5_cp310
  - pytng=0.3.3=py310he95d665_1
  - qhull=2020.2=h434a139_5
  - qt-main=5.15.8=h82b777d_17
  - qt6-main=6.6.1=h3af85ea_3
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=pyhd8ed1ab_1
  - rigimol=1.5=h3fd9d12_2
  - scikit-learn=1.6.0=py310h27f47ee_0
  - scipy=1.14.1=py310hfcf56fc_2
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=75.1.0=py310h06a4308_0
  - sip=6.7.12=py310hc6cd4ac_0
  - six=1.17.0=pyhd8ed1ab_0
  - slm_x509=2024.3=h9bf148f_3
  - snappy=1.2.1=h8bd8927_1
  - sqlite=3.47.2=h9eae976_0
  - sra-tools=3.2.1=h4304569_1
  - statsmodels=0.14.4=py310hf462985_0
  - sysroot_linux-64=2.17=h0157908_18
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tidynamics=1.1.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - tzdata=2024b=h04d1e81_0
  - unicodedata2=15.1.0=py310ha75aee5_1
  - urllib3=2.3.0=pyhd8ed1ab_0
  - vtk-m=1.8.0=h3fd9d12_2
  - waterdynamics=1.2.0=pyhd8ed1ab_1
  - wheel=0.44.0=py310h06a4308_0
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-cursor=0.1.4=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xkeyboard-config=2.42=h4ab18f5_0
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-inputproto=2.3.2=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.5=he73a12e_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h4bc722e_1
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-libxtst=1.2.5=h4bc722e_0
  - xorg-recordproto=1.14.2=hb9d3cd8_1003
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xf86vidmodeproto=2.3.1=hb9d3cd8_1005
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py310ha75aee5_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - absl-py==2.2.2
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - argparse==1.4.0
      - arrow==1.4.0
      - asttokens==3.0.0
      - astunparse==1.6.3
      - async-lru==2.0.5
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.2.0
      - comm==0.2.3
      - configparser==7.1.0
      - crowelab-pyir==1.5.0
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - dockq
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - flatbuffers==25.2.10
      - fqdn==1.5.1
      - freesasa==2.2.1
      - gast==0.6.0
      - gemmi==0.7.0
      - google-pasta==0.2.0
      - grpcio==1.71.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - ipykernel==7.0.1
      - ipython==8.37.0
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.9
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - keras
      - kiwisolver==1.4.8
      - lark==1.3.0
      - libclang==18.1.1
      - markdown==3.8
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib-inline==0.1.7
      - mdpeditor==1.2.5
      - mdurl==0.1.2
      - mistune==3.1.4
      - mpmath==1.3.0
      - namex==0.0.9
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - opt-einsum==3.4.0
      - optree==0.15.0
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parallelbar==2.4
      - parso==0.8.5
      - pdb-tools==2.5.0
      - pexpect==4.9.0
      - pillow==11.1.0
      - platformdirs==4.5.0
      - prodigy-prot
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - protobuf==5.29.4
      - psutil==7.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.1
      - python-json-logger==4.0.0
      - pytz==2024.2
      - pyyaml==6.0.3
      - pyzmq==26.2.0
      - referencing==0.37.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==13.9.4
      - rpds-py==0.27.1
      - scikit-spatial==8.1.0
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.8
      - stack-data==0.6.3
      - sympy==1.13.3
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.1.0
      - terminado==0.18.1
      - tinycss2==1.4.0
      - tornado==6.5.2
      - traitlets==5.14.3
      - typing-extensions==4.12.2
      - uri-template==1.3.0
      - wcwidth==0.2.14
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - wrapt==1.17.2
      - zmq==0.0.0
